import { expect, test, type Page } from '@playwright/test';

async function login(page: Page, email: string, password = 'TestPassword123!') {
  await page.goto('/');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar na central' }).click();
  await expect(page.getByRole('heading', { name: 'Ordens de serviço.' })).toBeVisible();
}
async function logout(page: Page) {
  await page.getByRole('button', { name: 'Menu do usuário', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Sair', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Acesse sua conta' })).toBeVisible();
}

test('solicitação, atribuição, solução, email real, aceite, PDF e consulta', async ({ browser }) => {
  const requester = await browser.newContext({ acceptDownloads: true }); const admin = await browser.newContext(); const technician = await browser.newContext();
  const requesterPage = await requester.newPage(); const adminPage = await admin.newPage(); const technicianPage = await technician.newPage();
  await login(requesterPage, 'ana@example.com'); await requesterPage.getByRole('link', { name: 'Nova ordem' }).click();
  await requesterPage.getByLabel('Título do chamado').fill('Computador não conecta à rede');
  await requesterPage.getByLabel('Descrição', { exact: true }).fill('A conexão foi interrompida e o computador não acessa a rede.');
  await requesterPage.getByRole('button', { name: 'Abrir ordem de serviço' }).click();
  await expect(requesterPage.getByRole('heading', { name: 'Computador não conecta à rede' })).toBeVisible();
  const orderPath = new URL(requesterPage.url()).pathname;
  const downloadPromise = requesterPage.waitForEvent('download'); await requesterPage.getByRole('link', { name: 'Baixar PDF' }).click();
  expect((await downloadPromise).suggestedFilename()).toMatch(/^OS-\d+\.pdf$/);
  await login(adminPage, 'admin@example.com', 'InitialAdmin123!'); await adminPage.goto(orderPath);
  await adminPage.getByLabel('Técnico', { exact: true }).selectOption({ label: 'Carlos Técnico' });
  await adminPage.getByRole('button', { name: 'Atribuir OS', exact: true }).click();
  await expect(adminPage.getByText('Atribuído a Carlos Técnico', { exact: true })).toBeVisible();
  await login(technicianPage, 'carlos@example.com'); await technicianPage.goto(orderPath);
  await technicianPage.getByLabel('Solução realizada').fill('Cabo de rede substituído. Conexão e acesso verificados com sucesso.');
  await technicianPage.getByRole('button', { name: 'Resolver e solicitar aceite' }).click();
  await expect(technicianPage.getByText('Email de aceite enviado.', { exact: true })).toBeVisible();
  const messages = await (await technicianPage.request.get('http://127.0.0.1:18025/api/v1/messages')).json();
  expect(messages.messages).toHaveLength(1);
  const email = await (await technicianPage.request.get(`http://127.0.0.1:18025/api/v1/message/${messages.messages[0].ID}`)).json();
  expect(email.To[0].Address).toBe('ana@example.com'); expect(email.HTML).toContain('cid:acceptance-qr');
  const raw = await (await technicianPage.request.get(`http://127.0.0.1:18025/api/v1/message/${messages.messages[0].ID}/raw`)).text();
  expect(raw).toContain('image/png');
  const confirmationLink = email.Text.match(/http:\/\/127\.0\.0\.1:3317\/confirmacao\/[a-f0-9]{64}/)![0];
  const publicContext = await browser.newContext({ colorScheme: 'dark' }); const confirmation = await publicContext.newPage();
  await confirmation.goto(confirmationLink); await expect(confirmation.getByRole('heading', { name: 'O problema foi resolvido?' })).toBeVisible();
  await expect(confirmation.locator('html')).toHaveAttribute('data-theme', 'dark');
  await confirmation.screenshot({ path: 'test-results/confirmation-dark.png', fullPage: true });
  await requesterPage.reload(); await expect(requesterPage.getByText('Aceite pendente', { exact: true })).toBeVisible();
  await confirmation.getByRole('button', { name: 'Confirmar atendimento' }).click();
  await expect(confirmation.getByRole('heading', { name: 'Aceite confirmado' })).toBeVisible();
  await requesterPage.reload(); await expect(requesterPage.getByText('Aceite confirmado', { exact: true })).toBeVisible();
  await requesterPage.screenshot({ path: 'test-results/order-desktop.png', fullPage: true });
  const order = await (await requesterPage.request.get(orderPath.replace('/ordens/', '/api/orders/'))).json();
  await requesterPage.goto('/'); await requesterPage.getByLabel('Número da OS', { exact: true }).fill(String(order.number));
  await requesterPage.getByRole('button', { name: 'Consultar', exact: true }).click();
  await expect(requesterPage.getByRole('link', { name: /Computador não conecta/ })).toBeVisible();
  await requesterPage.screenshot({ path: 'test-results/list-desktop.png', fullPage: true });
  await requesterPage.setViewportSize({ width: 390, height: 844 }); await requesterPage.screenshot({ path: 'test-results/list-mobile.png', fullPage: true });
  expect(await requesterPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await requester.close(); await admin.close(); await technician.close(); await publicContext.close();
});

test('dashboard, chamados e detalhes atualizam por eventos; som, reconexão e temas', async ({ browser }) => {
  const adminContext = await browser.newContext({ colorScheme: 'light' });
  await adminContext.addInitScript(() => {
    const state = window as unknown as { soundCount: number }; state.soundCount = 0;
    const original = AudioContext.prototype.createOscillator;
    AudioContext.prototype.createOscillator = function () { state.soundCount++; return original.call(this); };
  });
  const requesterContext = await browser.newContext({ colorScheme: 'light' });
  const techContext = await browser.newContext({ colorScheme: 'light' });
  const admin = await adminContext.newPage(); const requester = await requesterContext.newPage(); const tech = await techContext.newPage();
  await login(admin, 'admin@example.com', 'InitialAdmin123!');
  await expect(admin.getByText('Atualização conectada', { exact: true })).toBeVisible();
  await admin.getByRole('link', { name: 'Dashboard', exact: true }).click();
  await expect(admin.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible();
  const previous = Number(await admin.getByTestId('metric-dailyTotal').innerText());
  await expect.poll(() => admin.evaluate(() => (window as unknown as { soundCount: number }).soundCount)).toBe(0);
  await admin.getByRole('button', { name: 'Ativar som', exact: true }).click();
  await expect(admin.getByRole('button', { name: 'Desativar som', exact: true })).toBeVisible();
  await admin.getByRole('button', { name: 'Usar tema escuro', exact: true }).click();
  await expect(admin.locator('html')).toHaveAttribute('data-theme', 'dark');
  const clock = await admin.getByLabel('Hora de Brasília').innerText();
  await expect.poll(() => admin.getByLabel('Hora de Brasília').innerText()).not.toBe(clock);
  await login(requester, 'ana@example.com'); await login(tech, 'carlos@example.com');
  await expect(requester.getByLabel('Solicitante', { exact: true })).toHaveCount(0);
  await expect(requester.getByRole('link', { name: 'Dashboard', exact: true })).toHaveCount(0);
  await requester.getByRole('link', { name: 'Nova ordem' }).click();
  await expect(requester.getByLabel('Título do chamado')).toHaveAttribute('maxlength', '50');
  await expect(requester.getByLabel('Descrição', { exact: true })).toHaveAttribute('maxlength', '255');
  await requester.getByLabel('Título do chamado').fill('Atualização automática do chamado');
  await requester.getByLabel('Descrição', { exact: true }).fill('Chamado para conferir eventos e acompanhamento.');
  await requester.getByRole('button', { name: 'Abrir ordem de serviço' }).click();
  await expect(requester.getByRole('heading', { name: 'Atualização automática do chamado' })).toBeVisible();
  const orderPath = new URL(requester.url()).pathname;
  await expect(admin.getByTestId('metric-dailyTotal')).toHaveText(String(previous + 1));
  await expect(admin.getByText(/Novo chamado recebido:/)).toBeVisible();
  await expect.poll(() => admin.evaluate(() => (window as unknown as { soundCount: number }).soundCount)).toBe(1);
  await admin.screenshot({ path: 'test-results/dashboard-dark-desktop.png', fullPage: true });
  await admin.getByLabel('Ano', { exact: true }).fill('2000'); await admin.getByLabel('Mês', { exact: true }).selectOption('1');
  await admin.getByRole('button', { name: 'Aplicar período' }).click();
  await expect(admin.getByTestId('metric-monthlyTotal')).toHaveText('0');
  await expect(admin.getByTestId('metric-dailyTotal')).toHaveText(String(previous + 1));
  await admin.getByRole('link', { name: 'Chamados', exact: true }).click();
  await admin.getByRole('link', { name: /Atualização automática do chamado/ }).click();
  await admin.getByLabel('Técnico', { exact: true }).selectOption({ label: 'Carlos Técnico' });
  await admin.getByRole('button', { name: 'Atribuir OS', exact: true }).click();
  await expect(requester.getByText('Atribuído a Carlos Técnico', { exact: true })).toBeVisible();
  await expect(tech.getByRole('link', { name: /Atualização automática do chamado/ })).toBeVisible();
  await tech.getByRole('link', { name: /Atualização automática do chamado/ }).click();
  await tech.getByRole('button', { name: 'Usar tema escuro', exact: true }).click();
  await expect(tech.locator('html')).toHaveAttribute('data-theme', 'dark');
  await tech.getByLabel('Solução realizada').fill('Atendimento concluído e funcionamento confirmado.');
  await tech.getByRole('button', { name: 'Resolver e solicitar aceite' }).click();
  await expect(requester.getByText('Aceite pendente', { exact: true })).toBeVisible();
  await expect.poll(() => admin.evaluate(() => (window as unknown as { soundCount: number }).soundCount)).toBe(1);
  await requester.getByRole('link', { name: 'Ordens de serviço', exact: true }).click();
  const details = await (await requester.request.get(orderPath.replace('/ordens/', '/api/orders/'))).json();
  await requester.getByLabel('Número da OS', { exact: true }).fill(String(details.number));
  await requester.getByRole('button', { name: 'Consultar', exact: true }).click();
  await expect(requester.locator('tbody tr')).toHaveCount(1);
  await admin.getByRole('link', { name: 'Dashboard', exact: true }).click();
  await expect(admin.getByTestId('metric-dailyTotal')).toHaveText(String(previous + 1));
  await adminContext.setOffline(true);
  await requester.getByRole('link', { name: 'Nova ordem' }).click();
  await requester.getByLabel('Título do chamado').fill('Chamado durante desconexão');
  await requester.getByLabel('Descrição', { exact: true }).fill('Aparece no dashboard após reconectar.');
  await requester.getByRole('button', { name: 'Abrir ordem de serviço' }).click();
  await expect(requester.getByRole('heading', { name: 'Chamado durante desconexão' })).toBeVisible();
  await adminContext.setOffline(false);
  await expect(admin.getByTestId('metric-dailyTotal')).toHaveText(String(previous + 2), { timeout: 15_000 });
  await expect(admin.getByText('Atualização conectada', { exact: true })).toBeVisible();
  await admin.reload(); await expect(admin.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(admin.getByRole('button', { name: 'Ativar som', exact: true })).toBeVisible();
  await admin.getByRole('button', { name: 'Usar tema claro', exact: true }).click();
  await expect(admin.locator('html')).toHaveAttribute('data-theme', 'light');
  await admin.screenshot({ path: 'test-results/dashboard-light-desktop.png', fullPage: true });
  await admin.getByRole('button', { name: 'Usar tema escuro', exact: true }).click();
  await admin.setViewportSize({ width: 390, height: 844 }); await admin.screenshot({ path: 'test-results/dashboard-dark-mobile.png', fullPage: true });
  expect(await admin.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await logout(admin);
  await login(admin, 'ana@example.com'); await expect(admin.locator('html')).toHaveAttribute('data-theme', 'light');
  await logout(admin);
  await login(admin, 'admin@example.com', 'InitialAdmin123!'); await expect(admin.locator('html')).toHaveAttribute('data-theme', 'dark');
  await requester.goto('/dashboard'); await expect(requester).toHaveURL(/\/ordens$/);
  expect((await requester.request.get('/api/dashboard?year=2026&month=10')).status()).toBe(403);
  await adminContext.close(); await requesterContext.close(); await techContext.close();
});

test('eventos preservam filtros e formulários ainda não enviados', async ({ browser }) => {
  const requesterContext = await browser.newContext({ colorScheme: 'light' }); const adminContext = await browser.newContext({ colorScheme: 'light' });
  const requester = await requesterContext.newPage(); const admin = await adminContext.newPage();
  await login(requester, 'ana@example.com'); await login(admin, 'admin@example.com', 'InitialAdmin123!');
  const session = await (await requester.request.get('/api/auth/me')).json();
  async function create(title: string) {
    const response = await requester.request.post('/api/orders', { headers: { 'X-CSRF-Token': session.csrfToken, Origin: 'http://127.0.0.1:3317' }, data: { title, description: 'Descrição para conferir preservação da tela.' } });
    expect(response.status()).toBe(201); return response.json();
  }
  const order = await create('Preservação da consulta');
  await requester.getByLabel('Número da OS', { exact: true }).fill(String(order.number)); await requester.getByRole('button', { name: 'Consultar', exact: true }).click();
  await expect(requester.locator('tbody tr')).toHaveCount(1);
  await admin.goto(`/ordens/${order.id}`); await admin.getByLabel('Técnico', { exact: true }).selectOption({ label: 'Carlos Técnico' });
  await admin.getByRole('button', { name: 'Atribuir OS', exact: true }).click();
  await expect(requester.getByText('Atribuído a Carlos Técnico', { exact: true })).toBeVisible();
  await expect(requester.getByLabel('Número da OS', { exact: true })).toHaveValue(String(order.number));
  await admin.getByLabel('Técnico', { exact: true }).selectOption({ label: 'Diana Técnica' });
  const listUpdate = requester.waitForResponse(response => response.url().includes(`/api/orders?number=${order.number}&page=1`));
  const detailUpdate = admin.waitForResponse(response => response.url().endsWith(`/api/orders/${order.id}`) && response.request().method() === 'GET');
  await create('Outro chamado durante consulta'); await listUpdate; await detailUpdate;
  await expect(requester.locator('tbody tr')).toHaveCount(1);
  await expect(requester.getByRole('link', { name: /Outro chamado durante consulta/ })).toHaveCount(0);
  await expect(admin.getByLabel('Técnico', { exact: true }).locator('option:checked')).toHaveText('Diana Técnica');
  await requester.getByRole('link', { name: 'Nova ordem' }).click();
  await requester.getByLabel('Título do chamado').fill('Rascunho ainda não enviado'); await requester.getByLabel('Descrição', { exact: true }).fill('Texto que deve continuar no formulário.');
  await admin.getByRole('button', { name: 'Reatribuir OS', exact: true }).click();
  await expect(admin.getByText('Atribuído a Diana Técnica', { exact: true })).toBeVisible();
  const adminSession = await (await admin.request.get('/api/auth/me')).json();
  const technicians = await (await admin.request.get('/api/technicians')).json();
  const carlos = technicians.find((technician: { name: string }) => technician.name === 'Carlos Técnico');
  const reassigned = await admin.request.post(`/api/orders/${order.id}/assign`, {
    headers: { 'X-CSRF-Token': adminSession.csrfToken, Origin: 'http://127.0.0.1:3317' }, data: { technicianId: carlos.id },
  });
  expect(reassigned.status()).toBe(200);
  await expect(admin.getByLabel('Técnico', { exact: true }).locator('option:checked')).toHaveText('Carlos Técnico');
  await expect(requester.getByLabel('Título do chamado')).toHaveValue('Rascunho ainda não enviado');
  await expect(requester.getByLabel('Descrição', { exact: true })).toHaveValue('Texto que deve continuar no formulário.');
  await requester.getByRole('button', { name: 'Usar tema escuro', exact: true }).click();
  await requester.screenshot({ path: 'test-results/requester-dark-form.png', fullPage: true });
  await requesterContext.close(); await adminContext.close();
});
test('administrador cria conta e solicitante troca senha temporária', async ({ browser }) => {
  const adminContext = await browser.newContext(); const admin = await adminContext.newPage();
  await login(admin, 'admin@example.com', 'InitialAdmin123!'); await admin.getByRole('link', { name: 'Usuários', exact: true }).click();
  await admin.getByLabel('Nome', { exact: true }).fill('Elisa Solicitante'); await admin.getByLabel('Email', { exact: true }).fill('elisa@example.com');
  await admin.getByLabel('Senha temporária', { exact: true }).fill('TemporaryPass123!'); await admin.getByRole('button', { name: 'Criar conta' }).click();
  await expect(admin.getByText('Elisa Solicitante', { exact: true })).toBeVisible();
  const context = await browser.newContext(); const page = await context.newPage(); await page.goto('/');
  await page.getByLabel('Email', { exact: true }).fill('elisa@example.com'); await page.getByLabel('Senha', { exact: true }).fill('TemporaryPass123!');
  await page.getByRole('button', { name: 'Entrar na central' }).click(); await expect(page.getByRole('heading', { name: 'Defina sua senha' })).toBeVisible();
  await page.getByLabel('Senha atual', { exact: true }).fill('TemporaryPass123!'); await page.getByLabel('Nova senha', { exact: true }).fill('PermanentPass123!');
  await page.getByLabel('Repita a nova senha').fill('PermanentPass123!'); await page.getByRole('button', { name: 'Salvar nova senha' }).click();
  await expect(page.getByRole('heading', { name: 'Ordens de serviço.' })).toBeVisible(); await logout(page);
  await expect(page.getByRole('heading', { name: 'Acesse sua conta' })).toBeVisible();
  await adminContext.close(); await context.close();
});
